# Generated by Django 2.0.13 on 2019-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('code_material', models.CharField(db_index=True, max_length=50, unique=True)),
                ('img', models.CharField(max_length=500)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
